name: Ty Check & Deploy

on:
  push:
    paths:
      - '**/*.py'
      - '**/*.ipynb'
      - 'pyproject.toml'
      - 'uv.lock'

jobs:
  ty-check-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: ⚡ Install uv
        uses: astral-sh/setup-uv@v7

      - name: 🌳 Sync dependencies
        run: uv sync

      - name: 🚀 Run ty
        run: uvx ty check .

      - name: 📈 Push to Kaggle
        if: success()
        env:
          KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_API_TOKEN }}
        run: |
          TARGET_FILE=$(jq -r '.code_file' kernel-metadata.json)

          echo "Notebook file: $TARGET_FILE"
    
          # github.event.before = commit before push
          # github.sha = current commit
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          if echo "$CHANGED_FILES" | grep -F -q "$TARGET_FILE"; then
            echo "✅ Changes detected in $TARGET_FILE. Pushing to Kaggle..."
            uvx kaggle kernels push
          else
            echo "🚫 No changes detected in $TARGET_FILE. Skipping push."
          fi
