name: Build, Ty Check & Deploy

on:
  push:
    paths:
      - 'milestones/**.ipynb'
      - 'competition.ipynb'
      - 'scripts/merge.py'
      - '**/*.py'
      - 'pyproject.toml'
      - 'uv.lock'
  workflow_dispatch:

jobs:
  ty-check-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: ⚡ Install uv
        uses: astral-sh/setup-uv@v7

      - name: 🌳 Sync dependencies
        run: uv sync

      - name: 📒 Install nbformat
        run: |
          uv pip install nbformat

      - name: 🔨 Run Merge Script
        run: |
          uv run scripts/merge.py

      - name: 🔍 Run ty
        run: uvx ty check .

      - name: 💾 Commit and Push Result
        id: auto_commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Check if the output file has changed
          if [[ -n $(git status -s "24f2004142-notebook-t12026.ipynb") ]]; then
            git add "24f2004142-notebook-t12026.ipynb"
            git commit -m "🤖 Auto-generate submission notebook [skip ci]"
            git push
            echo "committed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes from merge script."
            echo "committed=false" >> $GITHUB_OUTPUT
          fi

      - name: 📈 Push to Kaggle
        if: success()
        env:
          KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_API_TOKEN }}
        run: |
          TARGET_FILE=$(jq -r '.code_file' kernel-metadata.json)

          echo "Notebook file: $TARGET_FILE"

          BEFORE_SHA=${{ github.event.before }}
          if [[ $BEFORE_SHA == "0000000000000000000000000000000000000000" ]]; then
              BEFORE_SHA="HEAD~1"
          fi

          # github.event.before = commit before push
          # github.sha = current commit
          CHANGED_FILES=$(git diff --name-only "$BEFORE_SHA" ${{ github.sha }})

          WAS_UPDATED_BY_SCRIPT="${{ steps.auto_commit.outputs.committed }}"

          if [[ "$WAS_UPDATED_BY_SCRIPT" == "true" ]]; then
             echo "✅ Merge script updated the notebook. Pushing to Kaggle..."
             uvx kaggle kernels push
          elif [[ "$CHANGED_FILES" == "$TARGET_FILE" || "$CHANGED_FILES" == "competition.ipynb" ]]; then
            echo "✅ Manual changes detected in $TARGET_FILE. Pushing to Kaggle..."
            uvx kaggle kernels push
          else
            echo "🚫 No changes detected in $TARGET_FILE. Skipping push."
          fi
